quarkus:
  http:
    port: ${PORT:8081}
    root-path: /dialog-service
  log:
    level: ${LOG_LEVEL:INFO}
    category:
      "com.dimas":
        level: ${OTUS_LOG_LEVEL:DEBUG}
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{3.}] (%t) %s%e%n"
  console:
    color: true
  datasource:
    jdbc: false
    db-kind: postgresql
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    reactive:
      url: ${DB_URL}
      max-size: ${DB_POOL_SIZE:80}
      idle-timeout: ${DB_POOL_IDLE_TIME:PT30s}
      max-lifetime: ${DB_POOL_MAX_TIME:PT60s}
  redis:
    hosts: ${REDIS_HOST:redis://localhost:6379}
    pool-cleaner-interval: 20
    pool-recycle-timeout: 20
  cache:
    redis:
      feed-cache:
        key-type: java.lang.String
        value-type: java.util.List
      expire-after-write: 600s

rest-logging:
  enabled: true
  append-body: true
